"use client";

import { FormEvent, useState } from "react";
import { Route, api, Navigate } from "./marketplace";

export default function AuthScreens({ route, navigate, onDone, onSessionRefresh, onSessionCleared, error, setError }: { route: Route; navigate: Navigate; onDone: () => Promise<void>; onSessionRefresh: () => Promise<void>; onSessionCleared: () => Promise<void> | void; error: string; setError: (value: string) => void }) {
  if (route.view === "forgot-password") return <ForgotPassword navigate={navigate} error={error} setError={setError} />;
  if (route.view === "reset-password") return <ResetPassword token={route.token || ""} navigate={navigate} onSessionCleared={onSessionCleared} error={error} setError={setError} />;
  if (route.view === "verify-email") return <VerifyEmail token={route.token || ""} navigate={navigate} onSessionRefresh={onSessionRefresh} error={error} setError={setError} />;
  return <AuthForm initialMode={route.mode || (route.next ? "login" : "register")} navigate={navigate} onDone={onDone} error={error} setError={setError} />;
}

function AuthForm({ initialMode, navigate, onDone, error, setError }: { initialMode: "login" | "register"; navigate: Navigate; onDone: () => Promise<void>; error: string; setError: (value: string) => void }) {
  const [mode, setMode] = useState(initialMode);
  const [pending, setPending] = useState(false);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [showDemo, setShowDemo] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setPending(true); setError("");
    try { await api(`/auth/${mode}`, { method: "POST", body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); await onDone(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Could not sign in."); }
    finally { setPending(false); }
  };
  return <section className="auth-screen"><div className="auth-panel"><h1>{mode === "login" ? "Welcome back" : "Start with a clear profile"}</h1><p className="auth-intro">{mode === "login" ? "Keep your work, orders, and applications in one place." : "Find focused work, publish an offer, and build a record of work you can carry forward."}</p><div className="auth-tabs"><button className={mode === "login" ? "selected" : ""} onClick={() => { setMode("login"); setError(""); }}>Sign in</button><button className={mode === "register" ? "selected" : ""} onClick={() => { setMode("register"); setError(""); }}>Create account</button></div><form className="form-stack" onSubmit={submit}><label>Email<input type="email" name="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>Password<input type="password" name="password" value={password} onChange={(event) => setPassword(event.target.value)} minLength={12} required /></label>{mode === "register" && <><label>Display name<input name="display_name" minLength={2} required /></label><label>Career stage<select name="career_stage"><option value="student">Student</option><option value="graduate">Graduate</option></select></label><input type="hidden" name="timezone" value="Asia/Kolkata" /></>}<button className="button button-primary button-wide" disabled={pending}>{pending ? "Working…" : mode === "login" ? "Sign in" : "Create account"}</button></form>{mode === "login" && <button className="auth-subtle-link" onClick={() => navigate({ view: "forgot-password", id: undefined })}>Forgot password?</button>}{error && <p className="notice notice-error" role="alert">{error}</p>}{process.env.NODE_ENV === "development" && <details className="demo-details"><summary onClick={() => setShowDemo(!showDemo)}>Development demo credentials</summary>{showDemo && <div className="demo-options"><p>Local-only accounts for testing marketplace roles.</p>{[["Worker", "ravi@skillhigh-campus.com"], ["Client", "maya@skillhigh-campus.com"], ["Admin", "admin@skillhigh-campus.com"]].map(([label, demoEmail]) => <button className="button button-secondary" type="button" key={label} onClick={() => { setMode("login"); setEmail(demoEmail); setPassword("skillhigh-demo-123"); }}>{label}</button>)}</div>}</details>}</div></section>;
}

function ForgotPassword({ navigate, error, setError }: { navigate: Navigate; error: string; setError: (value: string) => void }) {
  const [email, setEmail] = useState(""); const [pending, setPending] = useState(false); const [sent, setSent] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setPending(true); setError(""); try { await api("/auth/request-password-reset", { method: "POST", body: JSON.stringify({ email }) }); setSent(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not prepare a reset link."); } finally { setPending(false); } };
  return <section className="auth-screen"><div className="auth-panel"><button className="back-link" onClick={() => navigate({ view: "auth", mode: "login", id: undefined })}>Back to sign in</button><h1>Reset your password</h1><p className="auth-intro">If an account matches, a reset link has been prepared in the local development mail sink.</p>{sent ? <p className="notice notice-success" role="status">Check the development mail sink for the reset link.</p> : <form className="form-stack" onSubmit={submit}><label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><button className="button button-primary" disabled={pending}>{pending ? "Preparing…" : "Prepare reset link"}</button></form>}{error && <p className="notice notice-error" role="alert">{error}</p>}</div></section>;
}

function ResetPassword({ token: initialToken, navigate, onSessionCleared, error, setError }: { token: string; navigate: Navigate; onSessionCleared: () => Promise<void> | void; error: string; setError: (value: string) => void }) {
  const [token, setToken] = useState(initialToken); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [pending, setPending] = useState(false); const [done, setDone] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (password !== confirm) return setError("Passwords do not match."); setPending(true); setError(""); try { await api("/auth/reset-password", { method: "POST", body: JSON.stringify({ token, password }) }); await onSessionCleared(); setDone(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not reset your password."); } finally { setPending(false); } };
  return <section className="auth-screen"><div className="auth-panel"><h1>Choose a new password</h1>{done ? <><p className="notice notice-success" role="status">Password updated. Sign in again to continue.</p><button className="button button-primary" onClick={() => navigate({ view: "auth", mode: "login", id: undefined })}>Back to sign in</button></> : <form className="form-stack" onSubmit={submit}><label>Reset token<input value={token} onChange={(event) => setToken(event.target.value)} required /></label><label>New password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} minLength={12} required /></label><label>Confirm new password<input type="password" value={confirm} onChange={(event) => setConfirm(event.target.value)} minLength={12} required /></label><button className="button button-primary" disabled={pending}>{pending ? "Updating…" : "Set new password"}</button></form>}{error && <p className="notice notice-error" role="alert">{error}</p>}</div></section>;
}

function VerifyEmail({ token: initialToken, navigate, onSessionRefresh, error, setError }: { token: string; navigate: Navigate; onSessionRefresh: () => Promise<void>; error: string; setError: (value: string) => void }) {
  const [token, setToken] = useState(initialToken); const [pending, setPending] = useState(false); const [done, setDone] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setPending(true); setError(""); try { await api("/auth/verify-email", { method: "POST", body: JSON.stringify({ token }) }); await onSessionRefresh(); setDone(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not verify this email."); } finally { setPending(false); } };
  return <section className="auth-screen"><div className="auth-panel"><h1>{done ? "Email verified" : "Verify your email"}</h1>{done ? <button className="button button-primary" onClick={() => navigate({ view: "dashboard", id: undefined })}>Open workspace</button> : <form className="form-stack" onSubmit={submit}><label>Verification token<input value={token} onChange={(event) => setToken(event.target.value)} required /></label><button className="button button-primary" disabled={pending}>{pending ? "Verifying…" : "Verify email"}</button></form>}{error && <p className="notice notice-error" role="alert">{error}</p>}{!done && <button className="auth-subtle-link" onClick={() => navigate({ view: "auth", mode: "login", id: undefined })}>Back to sign in</button>}</div></section>;
}
