"use client";

import { useEffect, useState } from "react";
import { Navigate, PublicProfile, api, initials, imageFor, labelStatus, money } from "./marketplace";

export default function PublicProfileScreen({ id, navigate }: { id: number; navigate: Navigate }) {
  const [profile, setProfile] = useState<PublicProfile | null>(null); const [error, setError] = useState(""); const [copied, setCopied] = useState(false); const [shareError, setShareError] = useState(""); const [profileUrl, setProfileUrl] = useState("");
  useEffect(() => { let active = true; setProfileUrl(window.location.href); void api<PublicProfile>(`/people/${id}`).then((value) => { if (active) setProfile(value); }).catch((reason) => { if (active) setError(reason instanceof Error ? reason.message : "Member not found"); }); return () => { active = false; }; }, [id]);
  if (error) return <section className="empty-page"><p className="notice notice-error" role="alert">{error}</p><button className="button button-secondary" onClick={() => navigate({ view: "services", id: undefined })}>Back to services</button></section>;
  if (!profile) return <div className="page-loading">Loading profile…</div>;
  const share = async () => { const url = window.location.href; setShareError(""); try { await navigator.clipboard.writeText(url); setCopied(true); } catch { setCopied(false); setShareError("Copy is unavailable here. Select the profile URL below."); } };
  return <section className="public-profile-shell"><button className="back-link" onClick={() => navigate({ view: "services", id: undefined })}>Marketplace</button><div className="public-profile-heading"><div className="public-profile-identity"><span className="avatar avatar-large">{initials(profile.display_name)}</span><div><h1>{profile.display_name}</h1><p>{labelStatus(profile.career_stage)} · {profile.seller_rating ? `Rated ${profile.seller_rating} from ${profile.seller_review_count} seller review${profile.seller_review_count === 1 ? "" : "s"}` : "No reviews yet"}</p></div></div><button className="button button-secondary" onClick={() => void share()}>Share profile</button></div>{copied && <p className="notice notice-success" role="status">Profile link copied.</p>}{shareError && <div className="notice notice-neutral" role="status"><span>{shareError}</span><input aria-label="Public profile URL" value={profileUrl} readOnly onFocus={(event) => event.currentTarget.select()} /></div>}<div className="public-profile-grid"><div><section className="profile-section"><h2>About</h2><p>{profile.bio || "No bio added yet."}</p>{profile.skills.length ? <div className="tag-row">{profile.skills.map((skill) => <span className="tag" key={skill}>{skill}</span>)}</div> : null}</section><section className="profile-section"><h2>Offers</h2>{profile.services.length ? <div className="service-grid">{profile.services.map((service) => <article className="service-card" key={service.id}><button className="card-image-link" onClick={() => navigate({ view: "service", id: service.id })}><img src={imageFor(service)} alt={`${service.title} category context`} /></button><div className="card-content"><button className="card-title" onClick={() => navigate({ view: "service", id: service.id })}>{service.title}</button><p className="card-meta">{service.estimated_hours}h estimated</p><div className="card-price"><span>From</span><strong>{money(service.amount_minor, service.currency)}</strong></div></div></article>)}</div> : <p className="muted">No active offers yet.</p>}</section></div><aside className="profile-aside"><section className="proof-section"><h2>Public proof</h2>{profile.proofs.length ? profile.proofs.map((proof) => <article className="public-proof" id={`proof-${proof.id}`} key={proof.id}><strong>{proof.title}</strong><span>{proof.skills.join(" · ") || "Recorded work"}</span><small>Completed {new Date(proof.created_at).toLocaleDateString("en-IN")}</small></article>) : <p className="muted">No public proof shared yet.</p>}</section><section className="profile-section"><h2>Verified reviews</h2>{profile.seller_reviews.length ? profile.seller_reviews.map((review) => <blockquote key={review.id}><strong>Rated {review.rating} · {review.author_name}</strong><p>{review.body}</p></blockquote>) : <p className="muted">No reviews yet.</p>}</section></aside></div></section>;
}
